---
title: "Plots of tissue dissection times"
author: Tyler Sagendorf
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_depth: 2
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 3.4,
  fig.height = 2,
  out.height = "80%",
  out.width = "80%",
  dpi = 400,
  message = FALSE,
  warning = FALSE
)

save_plots <- dir.exists(paths = file.path("..", "..", "plots"))
```

```{r setup}
# Required packages
library(MotrpacRatTrainingPhysiologyData)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(scales)
```

```{r}
plot_dissection_times <- function(x, ymax = 12) {
  x <- x %>% 
    droplevels.data.frame() %>% 
    mutate(color = ifelse(aliquotdescription %in%
                            levels(DISSECTION_TIMES$aliquotdescription)[1:8], 
                          "anesthesia", "death"))
  
  # Mean +/- 2 SD
  p <- ggplot(x, aes(x = aliquotdescription, y = t_diff, color = color)) +
    stat_summary(geom = "crossbar", fatten = 1, linewidth = 0.5,
                 fun.data = ~ exp(mean_sdl(log(.x), mult = 2)),
                 width = 0.8) 
  
  # Modify appearance
  p <- p +
    scale_y_time(name = "Time Elapsed (min:sec)",
                 labels = scales::label_time(format = "%M:%S"),
                 expand = expansion(mult = 1e-2)) +
    labs(x = NULL) +
    coord_cartesian(ylim = c(0, ymax * 60)) +
    # light blue for tissues collected under anesthesia, grey for tissues
    # collected post-mortem
    scale_color_manual(values = c("#89CFF0", "grey50"),
                       labels = c("Under Anesthesia", "Post-Mortem")) +
    theme_minimal(base_size = 7, base_line_size = 0.3) +
    theme(axis.text = element_text(size = 7, color = "black"),
          axis.text.x = element_text(angle = 60, hjust = 1, vjust = 1),
          axis.title = element_text(size = 7.5, color = "black"),
          legend.position = "none",
          panel.grid.minor = element_blank(),
          panel.grid.major.y = element_blank(),
          axis.line = element_line(color = "black"),
          axis.ticks = element_line(color = "black"))
  
  return(p)
}
```

```{r, results='hide'}
# Create and save all plots
foo <- DISSECTION_TIMES %>% 
  nest(.by = c(age, sex)) %>% 
  arrange(age, sex) %>% 
  mutate(ymax = c(12, 16, 10, 10),
         plots = map2(.x = data, .y = ymax, .f = plot_dissection_times)) %>% 
  mutate(file_name = file.path("..", "..", "plots", 
                               sprintf("dissection_times_%s_%s.pdf", 
                                       age, tolower(sex))))
```

```{r eval=save_plots}
map2(.x = foo$file_name, .y = foo$plots, 
     .f = ~ ggsave(filename = .x, plot = .y, 
                   height = 2, width = 3.1, family = "ArialMT"))
```


# 6M Female

```{r}
foo %>% 
  filter(age == "6M", sex == "Female") %>%
  pull(plots) %>% 
  .[[1]]
```

# 6M Male

```{r}
foo %>% 
  filter(age == "6M", sex == "Male") %>% 
  pull(plots) %>% 
  .[[1]]
```

# 18M Female

```{r}
foo %>% 
  filter(age == "18M", sex == "Female") %>% 
  pull(plots) %>% 
  .[[1]]
```

# 18M Male

```{r}
foo %>% 
  filter(age == "18M", sex == "Male") %>% 
  pull(plots) %>% 
  .[[1]]
```


# Session Info

```{r}
sessionInfo()
```

