---
title: "Plots of fiber area by muscle and fiber type"
author: Tyler Sagendorf
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 1.8,
  fig.height = 1.5,
  out.height = "50%",
  out.width = "50%",
  dpi = 400,
  message = FALSE,
  warning = FALSE
)

save_plots <- dir.exists(paths = file.path("..", "..", "plots"))
```

```{r setup}
# Required packages
library(MotrpacRatTrainingPhysiologyData)
library(dplyr)
library(ggplot2)
library(latex2exp)
library(tidyr)
library(tibble)
library(purrr)

conf_df <- FIBER_AREA_EMM %>% 
  summary() %>% 
  as.data.frame() %>% 
  rename(any_of(c(lower.CL = "asymp.LCL",
                  upper.CL = "asymp.UCL",
                  response_mean = "response",
                  response_mean = "rate"))) %>% 
  separate(col = muscle_type, into = c("muscle", "type"), sep = "\\.") %>% 
  mutate(response = "Fiber CSA")

FIBER_AREA_STATS <- mutate(FIBER_AREA_STATS, response = "Fiber CSA")
```


# LG

## 6M Female

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "6M", sex = "Female", muscle = "LG",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA")) + 
  scale_y_continuous(name = TeX("LG CSA ($\\mu m^2$)"),
                     breaks = seq(1000, 3000, 500),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = c(700, 3300), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_LG_6M_female.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```

## 6M Male

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "6M", sex = "Male", muscle = "LG",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA")) + 
  scale_y_continuous(name = TeX("LG CSA ($\\mu m^2$)"),
                     breaks = 1000 * 1:5,
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = 1000 * c(1, 5), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_LG_6M_male.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```



## 18M Female

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "18M", sex = "Female", muscle = "LG",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 150) + 
  scale_y_continuous(name = TeX("LG CSA ($\\mu m^2$)"),
                     breaks = seq(1000, 3000, 500),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = 1000 * c(1, 3.25), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_LG_18M_female.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```


## 18M Male

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "18M", sex = "Male", muscle = "LG",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 120) + 
  scale_y_continuous(name = TeX("LG CSA ($\\mu m^2$)"),
                     breaks = seq(1000, 3500, 500),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = 1000 * c(1, 3.7), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_LG_18M_male.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```


# MG

## 6M Female

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "6M", sex = "Female", muscle = "MG",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 100) + 
  scale_y_continuous(name = TeX("MG CSA ($\\mu m^2$)"),
                     breaks = seq(800, 2800, 400),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = c(800, 2800), clip = "off") +
  theme(plot.margin = margin(t = 8, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_MG_6M_female.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```

## 6M Male

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "6M", sex = "Male", muscle = "MG",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA")) + 
  scale_y_continuous(name = TeX("MG CSA ($\\mu m^2$)"),
                     breaks = 1000 * 1:5,
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = 1000 * c(1, 5), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_MG_6M_male.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```



## 18M Female

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "18M", sex = "Female", muscle = "MG",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 120) + 
  scale_y_continuous(name = TeX("MG CSA ($\\mu m^2$)"),
                     breaks = seq(1000, 3000, 500),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = 1000 * c(1, 3.2), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_MG_18M_female.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```


## 18M Male

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "18M", sex = "Male", muscle = "MG",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 120) + 
  scale_y_continuous(name = TeX("MG CSA ($\\mu m^2$)"),
                     breaks = seq(1000, 3500, 500),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = 1000 * c(1, 3.6), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_MG_18M_male.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```


# PL

## 6M Female

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "6M", sex = "Female", muscle = "PL",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 100) + 
  scale_y_continuous(name = TeX("PL CSA ($\\mu m^2$)"),
                     breaks = seq(500, 2500, 500),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = c(500, 2650), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_PL_6M_female.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```

## 6M Male

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "6M", sex = "Male", muscle = "PL",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA")) + 
  scale_y_continuous(name = TeX("PL CSA ($\\mu m^2$)"),
                     breaks = 1000 * 1:5,
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = 1000 * c(0.7, 5), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_PL_6M_male.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```

## 18M Female

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "18M", sex = "Female", muscle = "PL",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 150) + 
  scale_y_continuous(name = TeX("PL CSA ($\\mu m^2$)"),
                     breaks = seq(1000, 3000, 500),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = 1000 * c(0.75, 3.2), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_PL_18M_female.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```

## 18M Male

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "18M", sex = "Male", muscle = "PL",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 140) + 
  scale_y_continuous(name = TeX("PL CSA ($\\mu m^2$)"),
                     breaks = seq(1000, 4000, 1000),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = c(800, 4050), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_PL_18M_male.pdf"), 
       height = 1.7, width = 1.4, family = "ArialMT")
```



# SOL

## 6M Female

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "6M", sex = "Female", muscle = "SOL",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 100) + 
  scale_y_continuous(name = TeX("SOL CSA ($\\mu m^2$)"),
                     breaks = seq(800, 1800, 200),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = c(800, 1840), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_SOL_6M_female.pdf"), 
       height = 1.7, width = 1.2, family = "ArialMT")
```

## 6M Male

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "6M", sex = "Male", muscle = "SOL",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA")) + 
  scale_y_continuous(name = TeX("SOL CSA ($\\mu m^2$)"),
                     breaks = seq(1200, 2200, 200),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = c(1200, 2200), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_SOL_6M_male.pdf"), 
       height = 1.7, width = 1.2, family = "ArialMT")
```

## 18M Female

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "18M", sex = "Female", muscle = "SOL",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA"),
                bracket.nudge.y = 90) + 
  scale_y_continuous(name = TeX("SOL CSA ($\\mu m^2$)"),
                     breaks = seq(800, 2000, 200),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = c(790, 2000), clip = "off") +
  theme(plot.margin = margin(t = 6, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_SOL_18M_female.pdf"),
       height = 1.7, width = 1.2, family = "ArialMT")
```

## 18M Male

```{r}
plot_fiber_type(x = FIBER_TYPES, 
                response = "fiber_area",
                age = "18M", sex = "Male", muscle = "SOL",
                conf = filter(conf_df, response == "Fiber CSA"),
                stats = filter(FIBER_AREA_STATS, response == "Fiber CSA")) + 
  scale_y_continuous(name = TeX("SOL CSA ($\\mu m^2$)"),
                     breaks = seq(1000, 3000, 500),
                     expand = expansion(mult = 5e-3)) +
  coord_cartesian(ylim = c(1000, 3000), clip = "off") +
  theme(plot.margin = margin(t = 3, r = 3, b = 3, l = 3))
```

```{r eval=save_plots}
ggsave(filename = file.path("..", "..", "plots", "fiber_CSA_SOL_18M_male.pdf"), 
       height = 1.7, width = 1.2, family = "ArialMT")
```


